version: "3.8"
services:
  sdl-app:
    container_name: sdl-app
    build:
      context: ..
      dockerfile: Dockerfile
    env_file:
      - ../.env
    environment:
      - NODE_ENV=production
      - DB_HOST=sdl-mysql
      - DB_NAME=sdl-db
      - REDIS_HOST=sdl-redis
      - MAIL_HOST=sdl-maildev
    ports:
      - "4000:4000"