version: "3.8"
services:
  sdl-mysql:
    container_name: sdl-mysql
    image: mysql:8.0.21
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ../packages/database/config/sql:/docker-entrypoint-initdb.d # Create Prod / Dev / Test Database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3307:3306'